### PR TITLE
Initial support for FileIO

### LINKED ISSUE #30: Feature request: `Base.show` for `OpenCV.Mat` image
@ashwani-rathee 

It's good to have `Base.show` method to display images in pluto.jl directly.

Currently, I implemented a simple(hacky) method for my needs to show images in pluto.jl
```julia
using ImageIO
using ImageShow
using ImageCore
using OpenCV

function Base.show(io::IO, ::MIME"image/png", opencv_img::OpenCV.Mat{UInt8})
	# opencv_img = OpenCV.cvtColor(opencv_img, OpenCV.COLOR_BGR2RGB)
	prmt_img::Array{UInt8, 3} = permutedims(opencv_img, (1, 3, 2))
	if size(prmt_img, 1) == 1
		img2d = dropdims(prmt_img; dims=1)
		img = colorview(Gray, float.(img2d)./255)
	else
		img = colorview(RGB, float.(prmt_img)./255)
	end
		
	Base.show(io, MIME"image/png"(), img)
end
```

### PR DESCRIPTION
**Pull request by rakeshksr**
This PR adds support for [FileIO.jl](https://github.com/JuliaIO/FileIO.jl) and `Base.show` method for `OpenCV.Mat` format.
Awaiting https://github.com/JuliaIO/FileIO.jl/pull/381 to merge.
Covers most of #34.
Closes #30 .

### CODE REVIEW

**Comment by rakeshksr** [comment]
Image preview working fine Pluto.jl, Ijulia and VS Code.

### VS Code
vscode

### Pluto.jl
pluto

### IJulia

ijulia

**Comment by rakeshksr** [comment]
@ashwani-rathee 
The PR https://github.com/JuliaIO/FileIO.jl/pull/381, which this PR relied on, has been successfully merged. With that dependency out of the way, I'd be grateful if you could take a look at this PR

**Comment by rakeshksr** [comment]
@ashwani-rathee Gentle bump

**Comment by ViralBShah** [comment]
@rakeshksr Would you be able to update this package and get these PRs merged. I am happy to give you commit access if you have the time to refresh the package.

**Comment by rakeshksr** [comment]
@ViralBShah I would be pleased to contribute to the merging of this pr.

**Comment by ViralBShah** [comment]
@rakeshksr What is the next step? CI seems to be passing.

**Comment by rakeshksr** [comment]
@ViralBShah Integration with the visualization packages like Plots.jl, Makie.jl and seamless interpolation with Images.jl ecosystem would be highly beneficial. 
FileIO side of the PR is already merged in https://github.com/JuliaIO/FileIO.jl/pull/381. 
I don't have sufficient permissions to commit changes to this repository.

**Comment by ViralBShah** [comment]
@rakeshksr Sent you invite to have commit access to JuliaImages

**Comment by rakeshksr** [comment]
@ViralBShah successfully joined in JuliaImages organization, but invitation to OpenCV.jl showing following error
image
I would be grateful if you could re-authorize write access to this repository.

**Review by johnnychen94 — APPROVED** [review]
It's great to see efforts made to OpenCV.jl

**Comment by ViralBShah** [comment]
@rakeshksr I added you to this repo then cancelled that invite and sent a second invite that was for the whole organization. Did you receice a second email?

**Comment by rakeshksr** [comment]
@ViralBShah I am still awaiting the necessary write access to this repository, which is currently blocking the merge of this pull request.

image

**Comment by ViralBShah** [comment]
Is this something we need to mention in the README or elsewhere in some docs?

**Comment by rakeshksr** [comment]
Docs are already committed to this PR.
https://juliaimages.org/OpenCV.jl/dev/Getting%20started%20with%20Images/

**Pull request merged**
