### PR TITLE
Docs Support

### PR DESCRIPTION
**Pull request by ashwani-rathee**
- Add Docs and Readme

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
Should we remove test run for nightly then given it's dependent on CxxWrap?

**Comment by timholy** [comment]
That sounds fine to me. I am wondering if testing nightly may be something we should all do less of; making compensatory changes in package code might obscure efforts to detect failures in backwards compatibility for Julia itself.

**Comment by ashwani-rathee** [comment]
Can we review it and if it looks okay, merge it? I don't have write access

**Comment by johnnychen94** [comment]
>  I don't have write access

Just gave you the maintain permission!

**Review by johnnychen94 — APPROVED** [review]

**Pull request merged**
